## 스프링 부트 서버 실행 시 자동으로 로딩되는 파일
## DB 설정 정보, 로깅 설정 정보, 커스텀 설정 정의 등 사용

# 쿼리 수행 관련 설정
spring:
  jpa:
    # 애플리케이션 실행 과정에 DB 쿼리할 일이 있으면 실행 구문을 모두 보여주는 옵션
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 애플리케이션 실행 시 테이블 생성 후 data.sql 파일 내 쿼리 실행하도록 하는 옵션
    defer-datasource-initialization: true

# H2 콘솔 활성화
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  h2:
    console:
      enabled: true
